spring:
  application:
    name: user-service
  profiles:
    active: minikube
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 9094


