eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_ADDRESS}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}