spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: Scary@123

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka