eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_ADDRESS}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
    prefer-ip-address: ${EUREKA_INSTANCE_PREFERIPADDRESS}
    instance-id: ${EUREKA_INSTANCE_HOSTNAME}
    non-secure-port: ${EUREKA_INSTANCE_NONSECUREPORT}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}